name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest  # 默认选择一个平台，可以在后续的步骤中覆盖

    steps:
      - name: 带子模块检出
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: 设置可复用字符串
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      # 编译项目 - Ubuntu
      - name: 编译项目 (Ubuntu)
        if: runner.os == 'Linux'  # 仅在 Ubuntu 上运行
        shell: bash
        run: |
          echo "正在编译 Ubuntu"
          cmake -B ${{ steps.strings.outputs.build-output-dir }}/malody \
                -DCMAKE_CXX_COMPILER=g++ \
                -DCMAKE_C_COMPILER=gcc \
                -DCMAKE_BUILD_TYPE=Release \
                -S ${{ github.workspace }}/malody
          cmake --build ${{ steps.strings.outputs.build-output-dir }}/malody --config Release

      # 编译项目 - Windows
      - name: 编译项目 (Windows)
        if: runner.os == 'Windows'  # 仅在 Windows 上运行
        shell: pwsh
        run: |
          Write-Host "正在编译 Windows"
          $buildOutputDir = "${{ steps.strings.outputs.build-output-dir }}"
          $buildOutputDir = $buildOutputDir -replace '/', '\\'
          $buildDir = Join-Path $buildOutputDir 'malody'
          Write-Host "构建目录: $buildDir"
          $sourceDir = Join-Path $env:GITHUB_WORKSPACE 'malody'
          Write-Host "源代码目录: $sourceDir"
          cmake -B "$buildDir" `
                -DCMAKE_CXX_COMPILER=g++ `
                -DCMAKE_C_COMPILER=gcc `
                -DCMAKE_BUILD_TYPE=Release `
                -S "$sourceDir"
          cmake --build "$buildDir" --config Release

      # 编译项目 - macOS
      - name: 编译项目 (macOS)
        if: runner.os == 'macOS'  # 仅在 macOS 上运行
        shell: bash
        run: |
          echo "正在编译 macOS"
          cmake -B ${{ steps.strings.outputs.build-output-dir }}/malody \
                -DCMAKE_CXX_COMPILER=clang++ \
                -DCMAKE_C_COMPILER=clang \
                -DCMAKE_BUILD_TYPE=Release \
                -S ${{ github.workspace }}/malody
          cmake --build ${{ steps.strings.outputs.build-output-dir }}/malody --config Release

      - name: 上传构建产物
        uses: actions/upload-artifact@v4.5.0
        with:
          name: build-artifacts
          path: ${{ steps.strings.outputs.build-output-dir }}/**
